### PR TITLE
Split and create standard phpunit actions + summary

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Seems to work, time to drop the last commit, rebase and fixup

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Btw in order to limit the action execution time (and because it's unlikely to have issues) I would recommend to test:
1. 1 DB on all supported PHP versions
2. all DBs on 1 PHP versions

Especially running Oracle on all (3 soon) supported php versions is unnecessary waste of resource

**Comment by nickvergessen** [comment]
Another thing we different in many apps is:
* We don't require phpunit in dependencies:
  https://github.com/nextcloud/spreed/blob/master/composer.json#L17-L21
* But install php in the action with it:
  https://github.com/nextcloud/spreed/blob/master/.github/workflows/phpunit.yml#L53-L59

It's especially helpful when the app has no-dev dependencies that need shipping, as it prevents having changed autoloader files etc locally all the time.

**Comment by skjnldsv** [comment]
> Another thing we different in many apps is:
> 
> * We don't require phpunit in dependencies:
>   [nextcloud/spreed@`master`/composer.json#L17-L21](https://github.com/nextcloud/spreed/blob/master/composer.json#L17-L21)
> * But install php in the action with it:
>   [nextcloud/spreed@`master`/.github/workflows/phpunit.yml#L53-L59](https://github.com/nextcloud/spreed/blob/master/.github/workflows/phpunit.yml#L53-L59)

The issue with that is that you suddenly fai to giev the dev the opportunity to use newer versions :)
But It's also going against the idea of a proper standard environement accross nextcloud. A good discussion to have I guess :wink: 

I don't have preferences, maybe we can discuss with other phpunit experts. Feel free to edit this PR @nickvergessen

**Comment by skjnldsv** [comment]
> * 1 DB on all supported PHP versions
> * all DBs on 1 PHP versions

Done

**Pull request merged**
